baseURL = 'https://cuttingboard.pessimisttech.com/'
languageCode = 'en-us'
title = 'Cutting Board'
theme = 'learn'

[Params]
  disableMermaid = true
  custom_css = ["css/custom.css"]
  themeVariant = 'blue'

[Params.Breadcrumb]
  enable = true # Enable breadcrumb block globally
  homeText = "Cutting Board" # Home node text

[outputs]
  home = [ "HTML", "RSS", "JSON"]

